name: 'Release'
description: 'Create releases when Pull Requests are merged.'

inputs:
  pr_number:
    description: 'The Pull Request number associated with this action run.'
    required: true

outputs:
  tag:
    description: 'Release tag'

runs:
  using: 'composite'
  steps:
    - run: ./check_git_repo.sh
      shell: bash
    - run: ./check_version_category_label.sh
      env:
        PR_NUMBER: ${{ inputs.pr_number }}
      shell: bash
      id: version-category
    - name: release
      shell: bash
      id: release
      if: steps.version-category.outputs.category != 'none'
      env:
        VERSION_CATEGORY: ${{ steps.version-category.outputs.category }}
        PR_NUMBER: ${{ inputs.pr_number }}
      run: ./release.sh "$VERSION_CATEGORY"
